[dev]
   command = "yarn dev"

[build]
  command = "yarn generate"
  publish = "dist"
  functions = "functions"
[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200
